---
title: "scrap"
author: "Todos"
format:
   html:
     toc: true
     html-math-method: katex
     embed-resources: true
     self-contained-math: true
     df-print: kable
editor: visual
---

```{r}
library(robotstxt)
library(rvest)
library(httr)
library(tibble)
library(stringr)
```

```{r}
paths_allowed("https://www.yourghoststories.com/")
```

```{r}
page = read_html("https://www.yourghoststories.com/real-ghost-story.php?story=1")

prueba = page %>%
  html_nodes(".storyinfo a") %>% # .storyinfo a # #story # #story p
  html_text()

prueba
```

```{r}
page = read_html("https://www.yourghoststories.com/real-ghost-stories.php")

categorias = page %>%
  html_nodes(".two_column_layout_col") %>%
  html_text() %>%
  str_split("\n") %>%
  unlist() %>%
  str_trim() %>%
  .[. != ""] %>%
  str_remove("\\s*\\(\\d+\\)$")

categorias
```

```{r}
paises = page %>%
  html_nodes(".column_layout:nth-child(53) .three_column_layout_col") %>%
  html_text() %>%
  str_split("\n") %>%
  unlist() %>%
  str_trim() %>%
  .[. != ""] %>%
  str_remove("\\s*\\(\\d+\\)$")

paises
```

```{r}
estados = page %>%
  html_nodes(".column_layout:nth-child(55) .three_column_layout_col") %>%
  html_text() %>%
  str_split("\n") %>%
  unlist() %>%
  str_trim() %>%
  .[. != ""] %>%
  str_remove("\\s*\\(\\d+\\)$")

estados
```

```{r}
detectar_valor <- function(texto, lista) {
  encontrado <- lista[str_detect(texto, fixed(lista, ignore_case = TRUE))]
  if (length(encontrado) > 0) {
    return(encontrado[1])
  } else {
    return(NA_character_)
  }
}
```

```{r}
titles <- character()
countries <- character()
states <- character()
types <- character()
descriptions <- character()

for (x in 1:10) {
  url = sprintf("https://www.yourghoststories.com/real-ghost-story.php?story=%d", x)
  
  if (status_code(GET(url)) == 200) {
    page <- read_html(url)
    
    title <- page %>%
      html_node(".storytitle") %>%
      html_text(trim = TRUE)
    titles <- c(titles, title)
    
    description <- page %>%
      html_node("#story") %>%
      html_text(trim = TRUE)
    descriptions <- c(descriptions, description)
    
    info_extra <- page %>%
      html_nodes(".storyinfo a") %>%
      html_text(trim = TRUE)
    
    country <- NA
    state <- NA
    category <- NA
    
    for (info in info_extra) {
      if (info %in% paises) {
        country <- info
      } else if (info %in% estados) {
        state <- info
      } else if (info %in% categorias) {
        category <- info
      }
    }
    
    countries <- c(countries, country)
    states <- c(states, state)
    types <- c(types, category)
  }
}

data_pages <- tibble(
  title = titles,
  country = countries,
  state = states,
  category = types,
  description = descriptions
)

data_pages$description <- gsub("\n", " ", data_pages$description)

data_pages
```

```{r}
write.table(
  data_pages,
  file = "../data/data_pages.csv",
  sep = "#$%#$%",
  row.names = FALSE,
  col.names = TRUE,
  quote = TRUE,
  fileEncoding = "UTF-8"
)
```

```{r}
lines <- readLines("../data/data_pages.csv", encoding = "UTF-8")
split_lines <- strsplit(lines, "#\\$%#\\$%")

data_pages_loaded <- as.data.frame(do.call(rbind, split_lines), stringsAsFactors = FALSE)

colnames(data_pages_loaded) <- data_pages_loaded[1, ]
data_pages_loaded <- data_pages_loaded[-1, ]
rownames(data_pages_loaded) <- NULL

data_pages_loaded
```

```{r}

```
